// Date: 2016/10/18 23:33:34
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModelMill extends ModelBase
{
  //fields
    RendererModel Shape1;
    RendererModel Shape2;
    RendererModel Shape3;
  
  public ModelModelMill()
  {
    textureWidth = 96;
    textureHeight = 64;
    
      Shape1 = new RendererModel(this, 0, 0);
      Shape1.addBox(-6F, -6F, -6F, 12, 6, 12);
      Shape1.setRotationPoint(0F, 18F, 0F);
      Shape1.setTextureSize(96, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new RendererModel(this, 0, 18);
      Shape2.addBox(-6F, -6F, -6F, 12, 6, 12);
      Shape2.setRotationPoint(0F, 18F, 0F);
      Shape2.setTextureSize(96, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 3.141593F);
      Shape3 = new RendererModel(this, 49, 0);
      Shape3.addBox(-5F, -9F, -1F, 2, 3, 2);
      Shape3.setRotationPoint(0F, 18F, 0F);
      Shape3.setTextureSize(96, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
  }
  
  private void setRotation(RendererModel model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
